###

POST  http://localhost:3000/auth/register



{
    "username" : "arianaraste",
    "email" : "arian@gmail.com",
    "mobile" : "09152056577",
    "password" : "78627831",
    "confirm_passwoed" : "78627831"
}
###
POST  http://localhost:3000/auth/login
Content-Type: application/json
{
    "username" : "arianaraste",
    "password" : "78627831",
    
}